[build]
  publish = "build"
  command = "CI= npm run build"

[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/manifest.json"
to = "/manifest.json"
status = 200

[[redirects]]
from = "/asset-manifest.json"
to = "/asset-manifest.json"
status = 200

[[redirects]]
from = "/logo.png"
to = "/logo.png"
status = 200

[[redirects]]
from = "/favicon.ico"
to = "/favicon.ico"
status = 200

[[redirects]]
from = "/service-worker.js"
to = "/service-worker.js"
status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true